### ISSUE TITLE
Frequent unhandled exception pop-ups

### ISSUE THREAD

**Issue by erictbar** [kennethsible/jellyfin-rpc#2]
I am frequently recieving this error when the process is running in the tray:

```
Failed to execute script 'main' due to unhandled exception:
'NoneType object has no attribute 'write'

Traceback (most recent call last):
  File "urllib3\connection.py", line 198, in _new_conn
  File "urllib3\util\connection.py", line 60, in create_connection
  File "socket.py", line 976, in getaddrinfo
socket.gaierror: [Errno 11002] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 793, in urlopen
  File "urllib3\connectionpool.py", line 491, in _make_request
  File "urllib3\connectionpool.py", line 467, in _make_request
  File "urllib3\connectionpool.py", line 1099, in _validate_conn
  File "urllib3\connection.py", line 616, in connect
  File "urllib3\connection.py", line 205, in _new_conn
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x00000179667C2990>: Failed to resolve 'subdomain.example.com' ([Errno 11002] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 847, in urlopen
  File "urllib3\util\retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='subdomain.example.com', port=443): Max retries exceeded with url: /jellyfin/Users (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000179667C2990>: Failed to resolve 'subdomain.example.com' ([Errno 11002] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multiprocessing\process.py", line 314, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "jellyfin_rpc.py", line 226, in main
  File "jellyfin_rpc.py", line 126, in set_discord_rpc
  File "jellyfin_rpc.py", line 58, in get_jellyfin_api
  File "jellyfin_rpc.py", line 41, in get_user_id
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 519, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='subdomain.examplecom', port=443): Max retries exceeded with url: /jellyfin/Users (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000179667C2990>: Failed to resolve 'subdomain.example.com' ([Errno 11002] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 224, in <module>
  File "PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 50, in _freeze_support
  File "multiprocessing\spawn.py", line 122, in spawn_main
  File "multiprocessing\spawn.py", line 135, in _main
  File "multiprocessing\process.py", line 329, in _bootstrap
AttributeError: 'NoneType' object has no attribute 'write'

```

The status stops displaying when this happens. Opening the app and toggling disconnect/connect will allow Discord to display the status again.

**Comment by kennethsible** [comment]
So you can get the RPC to work, but the status sometimes disappears when the GUI is minimized. Is this correct? It seems that the GET request for the user ID ([L41](https://github.com/kennethsible/jellyfin-rpc/blob/7db606de53ced903fb0bde6ca810929d5460a37e/jellyfin_rpc.py#L41)) has failed, which is needed to access the Jellyfin API for your server.

```
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x00000179667C2990>: Failed to resolve 'subdomain.example.com' ([Errno 11002] getaddrinfo failed)
```
I am not sure where 'subdomain.example.com' is coming from. Could you try changing the `log_level` in the INI file to `DEBUG`. What is the output of the log file after you get the error message again? Are you using SSL (https) to access your Jellyfin server?

**Comment by erictbar** [comment]
'subdomain.example.com' is just my server URL redacted. Yes, https, but with a reverse proxy, not from within Jellyfin, as well as a base URL, so `https://subdomain.example.com/jellyfin` It seems to happen most often when Discord is minimized, and possibly also when content starts playing. I updated to 1.2.4 of your app and will get back to you with debug logs. It seems to be happening in bursts, and then not at all for awhile.

**Comment by erictbar** [comment]
Same error, which pops up in a window, and nothing is being written to `jellyfin_rpc.log` even with `log_level = DEBUG`

**Comment by kennethsible** [comment]
Ah, there must be a write permission error for the log file, because mine is also empty outside of the development environment. I'll need to look into that as well. In the meantime, can you try pinging your Jellyfin API with a GET request for `/Users` (see below). My Jellyfin URL is a subdomain, https://jellyfin.example.com, so maybe the API call is slightly different for subfolders.

PowerShell (Windows):
```
curl -Method GET -Uri "https://subdomain.example.com/jellyfin/Users" `
  -Headers @{
    "Accept" = "application/json";
    "X-Emby-Token" = "XXXXXX"
  } `
```

Terminal (Linux/Mac):
```
curl -X GET "https://subdomain.example.com/jellyfin/Users" \
  -H "Accept: application/json" \
  -H "X-Emby-Token: XXXXXX" \
```

You'll need to replace https://subdomain.example.com with your Jellyfin URL and `XXXXXX` with your Jellyfin API token. If the output of `curl` is empty (with an SSL or 404 error), there is an issue connecting to the API. I'll check the API documentation to see if there's anything specific about accessing the API using subfolders.

**Comment by erictbar** [comment]
I had issues with the PowerShell command, it would lead to a line asking for more text. I asked GPT and it told me to run this instead:
```
Invoke-RestMethod -Uri "https://subdomain.example.com/jellyfin/Users" `
  -Method GET `
  -Headers @{
    "Accept" = "application/json";
    "X-Emby-Token" = "XXXXXX"
  }

```

Which displayed an output of my two users, info, configuration for either. Then ran the Linux command on WSL (without the trailing `\` and it did similarly.

In case it wasn't clear, this issue does not occur all the time and I often can correctly get my status. It seems to hiccup occasionally though, which is an issue I have been having with my server (perhaps something involving Caddy or my DDNS?). 

Perhaps when this error occurs it can ignore the pop-up and try again in 10 seconds? If that is something that can be done.

**Comment by kennethsible** [comment]
I wonder if Caddy (or your DNS or something else) is rate limiting your Jellyfin server since some requests are blocked but others are successful. Anyway, I pushed a commit (bfea1d1) to ignore the pop-up and try again in 10 seconds. I already had a try-except statement for the Jellyfin API, but I wasn't catching `RequestException` (the parent of `ConnectionError`). I'll find some time later today to investigate the empty log files, and once that's fixed, I'll upload a new release.

**Comment by kennethsible** [comment]
I added more exception handling for the Jellyfin API (bfea1d1 & 486c673), and I fixed the empty log files (61c5cad). Hopefully, the [v1.2.5 release](https://github.com/kennethsible/jellyfin-rpc/releases/tag/v1.2.5) works for you since any `RequestException` should trigger a retry to connect to the Jellyfin API.

**Comment by erictbar** [comment]
I was running (https://github.com/kennethsible/jellyfin-rpc/commit/bfea1d185ab916987b69c3d8c2f425f07b0d4ad7) compiled since last night and I didn't have any of the normal issues, so is working better. 

However, not sure if this deserves its own issue, but I am getting this whenever I play an mp3 with no metadata, that has been placed in a folder with other items that do have metadata (the songs with metadata have no issue).  Now running release 1.2.5. and the issue continues.

```
Traceback (most recent call last):
  File "multiprocessing\process.py", line 314, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "jellyfin_rpc.py", line 216, in main
  File "jellyfin_rpc.py", line 144, in set_discord_rpc
KeyError: 'Album'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 221, in <module>
  File "PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 50, in _freeze_support
  File "multiprocessing\spawn.py", line 120, in spawn_main
  File "multiprocessing\spawn.py", line 133, in _main
  File "multiprocessing\process.py", line 329, in _bootstrap
AttributeError: 'NoneType' object has no attribute 'write'

```
It is still in a pop-up, though some things are being written to the log file:
[jellyfin_rpc.log](https://github.com/user-attachments/files/18102812/jellyfin_rpc.log)

**Comment by kennethsible** [comment]
I tried to avoid all pop-ups by using a custom excepthook to forward exceptions to the log file, but unfortunately it seems that a custom excepthook doesn't work with multiprocessing in Python. However, I will continue to try to surround everything necessary with try-except, even though Python libraries are not as well documented as other languages when it comes to what exceptions they can throw. I am also aware of the metadata problem since I recently started using my Jellyfin server to host Japanese music.

**Comment by kennethsible** [comment]
I added support for missing metadata and toggles to disable certain media types (915494f). In addition, album covers are now pulled from the [Cover Art Archive/API](https://wiki.musicbrainz.org/Cover_Art_Archive/API) via the MusicBrainz ID, so hopefully this will expand the music support enough! I will close this issue with the [v1.3.0 release](https://github.com/kennethsible/jellyfin-rpc/releases/tag/v1.3.0).

**Comment by kennethsible** [comment]
Note, you'll need to add `media_types = Movies,Shows,Music` to your INI file when you upgrade to v1.3.0!
